# Generated by Django 4.2.6 on 2023-11-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Обратная связь',
            },
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['course', 'id'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
